owner: koj-co
repo: upptime
user-agent: KojBot

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: schindler_P
    url: https://main.dm-cn-p.ioee10-cloud.cn/apps/cockpit/index.html#/
  - name: schindler-q
    url: https://main.dm-cn-q.ioee10-cloud.cn/apps/devicemanagement/index.html
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Secret Site
    url: $SECRET_SITE

# Add downtime notifications
# https://upptime.js.org/docs/notifications
notifications:
  - type: slack
    channel: C016QTU9S9Y
assignees:
  - AnandChowdhary

# Configure your status website
# http://localhost:3000/docs/configuration#status-website
status-website:
  cname: demo.upptime.js.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ericwang800
  #baseUrl: /healthcheck
  introTitle: "**upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
